apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-express-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/memrekaraaslan/nodejs-express-mysql.git
    targetRevision: master
    path: helm/nodejs-express-mysql
    helm:
      valueFiles:
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true